<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vishnuprabhu-PC" failures="2" tests="4" name="Surefire test" time="41.012" errors="0" timestamp="2024-02-15T15:45:14 IST">
  <testcase classname="academy.tests.ErrorValidationTest" name="IncorrectCredentialValidation" time="0.476">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at academy.tests.ErrorValidationTest.IncorrectCredentialValidation(ErrorValidationTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- IncorrectCredentialValidation -->
  <testcase classname="academy.tests.ErrorValidationTest" name="productNameErrorValidation" time="13.615"/>
  <testcase classname="academy.tests.SubmitOrderTest" name="submitOrder" time="14.333"/>
  <testcase classname="academy.tests.SubmitOrderTest" name="OrderHistoryTest" time="0.749">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at academy.tests.SubmitOrderTest.OrderHistoryTest(SubmitOrderTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- OrderHistoryTest -->
</testsuite> <!-- Surefire test -->
