<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vishnuprabhu-PC" failures="1" tests="2" name="Error Validations" time="29.89" errors="0" timestamp="2024-02-16T18:49:56 IST">
  <testcase classname="academy.tests.ErrorValidationTest" name="IncorrectCredentialValidation" time="0.727">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at academy.tests.ErrorValidationTest.IncorrectCredentialValidation(ErrorValidationTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- IncorrectCredentialValidation -->
  <testcase classname="academy.tests.ErrorValidationTest" name="productNameErrorValidation" time="14.092"/>
</testsuite> <!-- Error Validations -->
